"""changed address line 2 to nullable True

Revision ID: 48075f2194cf
Revises: 2735fd19e7dd
Create Date: 2023-07-04 23:20:54.564462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48075f2194cf'
down_revision = '2735fd19e7dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.alter_column('address_line_2',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.alter_column('address_line_2',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
